<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AgentCore\AgentCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenAI" Version="2.13.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>2fb656b9-fb75-4a41-9051-464fe07554e0</UserSecretsId>
  </PropertyGroup>

</Project>
